version: '3.6'
services:
  db:
    image: postgis/postgis
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - websh-database:/var/lib/postgresql/data
    networks:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: websh:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - config.env
    networks:
      - db
volumes:
  websh-database:
    driver: local
networks:
  db:
