# Generated by Django 4.1.4 on 2022-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('acronym', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('isp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuels', models.ManyToManyField(to='rockety.fuel')),
            ],
        ),
    ]
