# Generated by Django 4.1.4 on 2022-12-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=5, max_digits=19)),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rockety.fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('engines', models.ManyToManyField(to='rockety.engine')),
                ('tanks', models.ManyToManyField(to='rockety.tank')),
            ],
        ),
    ]
