# Generated by Django 4.1.4 on 2022-12-17 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0003_alter_tank_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='tank',
            name='capacity',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19),
        ),
    ]
