# Generated by Django 4.1.4 on 2022-12-17 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0005_alter_tank_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19, verbose_name='Volume (m³)'),
        ),
        migrations.AddField(
            model_name='tank',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19, verbose_name='Weight (kg)'),
        ),
    ]
