# Generated by Django 4.1.4 on 2022-12-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0006_tank_volume_tank_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='acronym',
            field=models.CharField(blank=True, max_length=32, verbose_name='Fuel'),
        ),
    ]
