# Generated by Django 4.1.4 on 2022-12-18 10:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0007_alter_fuel_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_mass', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19, verbose_name='Dry Mass (kg)')),
                ('name', models.CharField(max_length=512)),
                ('wet_mass', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19, verbose_name='Wet Mass (kg)')),
                ('stages', models.ManyToManyField(to='rockety.stage')),
            ],
        ),
    ]
