# Generated by Django 4.1.4 on 2022-12-18 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockety', '0009_rename_weight_tank_dry_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='dry_mass',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=19, verbose_name='Dry Mass (kg)'),
        ),
    ]
